<?php
/**
 * Server-side render template for the pizzapilot/delivery-checker block.
 *
 * Renders the trigger button (location-pin icon) and the dialog markup
 * with three render states — prompt, success, failure. Open/close
 * interaction, focus trapping, and AJAX wiring are added in Tasks 16.3
 * and 16.4. Until view.js implements the open handler, the dialog stays
 * hidden via the `hidden` attribute.
 *
 * @package Pizzapilot
 * @since   1.2.0
 *
 * @var array $attributes Block attributes (reserved for Pro-side overrides via the
 *                        pizzapilot_delivery_checker_block_strings filter — Task 16.8).
 */

if ( ! defined( 'WPINC' ) ) {
	die;
}

$pizzapilot_wrapper_attributes = function_exists( 'get_block_wrapper_attributes' )
	? get_block_wrapper_attributes( array( 'class' => 'pizzapilot-delivery-checker' ) )
	: 'class="pizzapilot-delivery-checker"';

/**
 * Filters the user-facing strings used by the delivery-checker block.
 *
 * Pro can hook this filter to swap in editor-configurable copy stored as
 * block attributes, without modifying the free plugin's render template.
 *
 * @since 1.2.0
 *
 * @param array $strings Map of slug => translated string.
 */
$pizzapilot_strings = apply_filters(
	'pizzapilot_delivery_checker_block_strings',
	array(
		'trigger_label'        => __( 'Check delivery to your postcode', 'pizzapilot' ),
		'close_label'          => __( 'Close', 'pizzapilot' ),
		'prompt_heading'       => __( 'Insert your postcode to check that we can deliver in your area.', 'pizzapilot' ),
		'postcode_label'       => __( 'Postcode', 'pizzapilot' ),
		'postcode_placeholder' => _x( 'e.g. SW1A 1AA', 'postcode input placeholder', 'pizzapilot' ),
		'submit_label'         => __( 'Check', 'pizzapilot' ),
		'success_message'      => __( 'Yes, we are delivering in your area!', 'pizzapilot' ),
		'failure_message'      => __( "Sorry! We can't deliver in your area but, you can choose to collect at the checkout", 'pizzapilot' ),
		'reset_label'          => __( 'Check another postcode', 'pizzapilot' ),
	)
);

$pizzapilot_uid         = function_exists( 'wp_unique_id' ) ? wp_unique_id( 'pizzapilot-dc-' ) : 'pizzapilot-dc-' . wp_rand( 1000, 9999 );
$pizzapilot_dialog_id   = $pizzapilot_uid . '-dialog';
$pizzapilot_heading_id  = $pizzapilot_uid . '-heading';
$pizzapilot_postcode_id = $pizzapilot_uid . '-postcode';
$pizzapilot_error_id    = $pizzapilot_uid . '-error';

$pizzapilot_location_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false">'
	. '<path fill="currentColor" d="M12 2a7 7 0 0 0-7 7c0 5.25 7 13 7 13s7-7.75 7-13a7 7 0 0 0-7-7zm0 9.5A2.5 2.5 0 1 1 12 6.5a2.5 2.5 0 0 1 0 5z"/>'
	. '</svg>';

$pizzapilot_close_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" focusable="false">'
	. '<path fill="currentColor" d="M19 6.4 17.6 5 12 10.6 6.4 5 5 6.4 10.6 12 5 17.6 6.4 19 12 13.4 17.6 19 19 17.6 13.4 12Z"/>'
	. '</svg>';

$pizzapilot_thumbs_up_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="48" height="48" aria-hidden="true" focusable="false">'
	. '<path fill="currentColor" d="M9 21h9a2 2 0 0 0 2-1.7l1.4-9A2 2 0 0 0 19.4 8H14V4a2 2 0 0 0-2-2 1 1 0 0 0-1 .6L7 11v10h2zm-7 0h3V11H2z"/>'
	. '</svg>';

$pizzapilot_thumbs_down_svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="48" height="48" aria-hidden="true" focusable="false">'
	. '<path fill="currentColor" d="M15 3H6a2 2 0 0 0-2 1.7L2.6 13.7A2 2 0 0 0 4.6 16H10v4a2 2 0 0 0 2 2 1 1 0 0 0 1-.6l4-8.4V3h-2zm7 0h-3v10h3z"/>'
	. '</svg>';

$pizzapilot_allowed_svg = array(
	'svg'  => array(
		'xmlns'       => true,
		'viewbox'     => true,
		'width'       => true,
		'height'      => true,
		'aria-hidden' => true,
		'focusable'   => true,
	),
	'path' => array(
		'd'    => true,
		'fill' => true,
	),
);
?>
<div <?php echo $pizzapilot_wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Output is generated by core get_block_wrapper_attributes(). ?>>
	<button
		type="button"
		class="pizzapilot-delivery-checker__trigger"
		aria-haspopup="dialog"
		aria-controls="<?php echo esc_attr( $pizzapilot_dialog_id ); ?>"
		aria-expanded="false"
		aria-label="<?php echo esc_attr( $pizzapilot_strings['trigger_label'] ); ?>"
		data-pizzapilot-open
	>
		<?php echo wp_kses( $pizzapilot_location_svg, $pizzapilot_allowed_svg ); ?>
	</button>

	<div
		id="<?php echo esc_attr( $pizzapilot_dialog_id ); ?>"
		class="pizzapilot-delivery-checker__modal"
		role="dialog"
		aria-modal="true"
		aria-labelledby="<?php echo esc_attr( $pizzapilot_heading_id ); ?>"
		hidden
	>
		<div class="pizzapilot-delivery-checker__overlay" data-pizzapilot-close></div>

		<div class="pizzapilot-delivery-checker__panel" role="document">
			<button
				type="button"
				class="pizzapilot-delivery-checker__close"
				aria-label="<?php echo esc_attr( $pizzapilot_strings['close_label'] ); ?>"
				data-pizzapilot-close
			>
				<?php echo wp_kses( $pizzapilot_close_svg, $pizzapilot_allowed_svg ); ?>
			</button>

			<div class="pizzapilot-delivery-checker__state pizzapilot-delivery-checker__state--prompt" data-pizzapilot-state="prompt">
				<h2 id="<?php echo esc_attr( $pizzapilot_heading_id ); ?>" class="pizzapilot-delivery-checker__heading">
					<?php echo esc_html( $pizzapilot_strings['prompt_heading'] ); ?>
				</h2>

				<form class="pizzapilot-delivery-checker__form" data-pizzapilot-form novalidate>
					<label for="<?php echo esc_attr( $pizzapilot_postcode_id ); ?>" class="screen-reader-text">
						<?php echo esc_html( $pizzapilot_strings['postcode_label'] ); ?>
					</label>
					<input
						type="text"
						id="<?php echo esc_attr( $pizzapilot_postcode_id ); ?>"
						class="pizzapilot-delivery-checker__input"
						name="postcode"
						placeholder="<?php echo esc_attr( $pizzapilot_strings['postcode_placeholder'] ); ?>"
						autocomplete="postal-code"
						autocapitalize="characters"
						spellcheck="false"
						aria-describedby="<?php echo esc_attr( $pizzapilot_error_id ); ?>"
						required
					/>
					<button type="submit" class="pizzapilot-delivery-checker__submit">
						<?php echo esc_html( $pizzapilot_strings['submit_label'] ); ?>
					</button>
				</form>

				<p
					id="<?php echo esc_attr( $pizzapilot_error_id ); ?>"
					class="pizzapilot-delivery-checker__error"
					role="alert"
					aria-live="polite"
					hidden
					data-pizzapilot-error
				></p>
			</div>

			<div class="pizzapilot-delivery-checker__state pizzapilot-delivery-checker__state--success" data-pizzapilot-state="success" hidden>
				<span class="pizzapilot-delivery-checker__icon pizzapilot-delivery-checker__icon--success">
					<?php echo wp_kses( $pizzapilot_thumbs_up_svg, $pizzapilot_allowed_svg ); ?>
				</span>
				<p class="pizzapilot-delivery-checker__message">
					<?php echo esc_html( $pizzapilot_strings['success_message'] ); ?>
				</p>
				<button type="button" class="pizzapilot-delivery-checker__reset" data-pizzapilot-reset>
					<?php echo esc_html( $pizzapilot_strings['reset_label'] ); ?>
				</button>
			</div>

			<div class="pizzapilot-delivery-checker__state pizzapilot-delivery-checker__state--failure" data-pizzapilot-state="failure" hidden>
				<span class="pizzapilot-delivery-checker__icon pizzapilot-delivery-checker__icon--failure">
					<?php echo wp_kses( $pizzapilot_thumbs_down_svg, $pizzapilot_allowed_svg ); ?>
				</span>
				<p class="pizzapilot-delivery-checker__message">
					<?php echo esc_html( $pizzapilot_strings['failure_message'] ); ?>
				</p>
				<button type="button" class="pizzapilot-delivery-checker__reset" data-pizzapilot-reset>
					<?php echo esc_html( $pizzapilot_strings['reset_label'] ); ?>
				</button>
			</div>
		</div>
	</div>
</div>
